export const brands = [
  {
    name: "Arçelik",
    color: "#E30613",
    country: "Türkiye",
    category: "Beyaz Eşya & Klima",
    desc: "Türkiye'nin en büyük beyaz eşya ve klima üreticisi. Buzdolabı, çamaşır makinesi, klima ve daha fazlası.",
  },
  {
    name: "Beko",
    color: "#003DA5",
    country: "Türkiye",
    category: "Beyaz Eşya & Klima",
    desc: "Arçelik'in uluslararası markası. Avrupa'nın en çok satan beyaz eşya markalarından biri.",
  },
  {
    name: "Vestel",
    color: "#0057A8",
    country: "Türkiye",
    category: "Beyaz Eşya & Klima",
    desc: "Türkiye'nin ikinci büyük beyaz eşya üreticisi. Klima, buzdolabı ve çamaşır makinesi üretir.",
  },
  {
    name: "Bosch",
    color: "#E20015",
    country: "Almanya",
    category: "Beyaz Eşya",
    desc: "Alman mühendisliği ile üretilen premium beyaz eşya ve ev aletleri markası.",
  },
  {
    name: "Siemens",
    color: "#009999",
    country: "Almanya",
    category: "Beyaz Eşya",
    desc: "Bosch Group bünyesinde premium segmentte faaliyet gösteren Alman marka.",
  },
  {
    name: "Samsung",
    color: "#1428A0",
    country: "Güney Kore",
    category: "Beyaz Eşya & Klima",
    desc: "Klima, buzdolabı ve çamaşır makinesi alanında dünya lideri Koreli teknoloji devi.",
  },
  {
    name: "LG",
    color: "#A50034",
    country: "Güney Kore",
    category: "Beyaz Eşya & Klima",
    desc: "Inverter klima ve akıllı beyaz eşya teknolojilerinde öncü Koreli marka.",
  },
  {
    name: "Daikin",
    color: "#005BAC",
    country: "Japonya",
    category: "Klima",
    desc: "Dünyanın en büyük klima üreticisi. Inverter ve VRV sistemleriyle sektör lideri.",
  },
  {
    name: "Mitsubishi",
    color: "#E60026",
    country: "Japonya",
    category: "Klima",
    desc: "Yüksek verimli ısı pompası ve klima sistemlerinde Japon kalitesi.",
  },
  {
    name: "Fujitsu",
    color: "#E4032E",
    country: "Japonya",
    category: "Klima",
    desc: "Enerji tasarruflu inverter klima sistemlerinde dünya markası.",
  },
  {
    name: "Miele",
    color: "#231F20",
    country: "Almanya",
    category: "Beyaz Eşya",
    desc: "Ultra premium segmentte Alman el işçiliği ile üretilen dayanıklı beyaz eşya.",
  },
  {
    name: "Electrolux",
    color: "#003087",
    country: "İsveç",
    category: "Beyaz Eşya",
    desc: "İsveç menşeli küresel beyaz eşya devi. Profesyonel ve ev serisi ürünler.",
  },
  {
    name: "Whirlpool",
    color: "#004B97",
    country: "ABD",
    category: "Beyaz Eşya",
    desc: "Dünyanın en büyük beyaz eşya üreticilerinden. Geniş ürün yelpazesi.",
  },
  {
    name: "Baymak",
    color: "#D0021B",
    country: "Türkiye",
    category: "Klima & Isıtma",
    desc: "Türkiye'nin kombi, ısı pompası ve klima alanında güçlü yerli markası.",
  },
  {
    name: "Alarko Carrier",
    color: "#003366",
    country: "Türkiye",
    category: "Klima",
    desc: "Endüstriyel ve konut tipi klima sistemlerinde Türkiye'nin köklü markası.",
  },
  {
    name: "Toshiba",
    color: "#E4032E",
    country: "Japonya",
    category: "Klima",
    desc: "Yüksek performanslı split ve multi-split klima sistemlerinde Japon markası.",
  },
  {
    name: "Panasonic",
    color: "#003087",
    country: "Japonya",
    category: "Klima",
    desc: "Nanoe X teknolojisi ile hava kalitesini artıran premium klima sistemleri.",
  },
  {
    name: "Grundig",
    color: "#E30613",
    country: "Türkiye/Almanya",
    category: "Beyaz Eşya",
    desc: "Arçelik bünyesinde faaliyet gösteren Alman kökenli premium beyaz eşya markası.",
  },
  {
    name: "Indesit",
    color: "#E30613",
    country: "İtalya",
    category: "Beyaz Eşya",
    desc: "Whirlpool bünyesinde uygun fiyatlı ve güvenilir beyaz eşya çözümleri.",
  },
  {
    name: "Zanussi",
    color: "#004B97",
    country: "İtalya/İsveç",
    category: "Beyaz Eşya",
    desc: "Electrolux bünyesinde İtalyan tasarımı ile güvenilir beyaz eşya ürünleri.",
  },
] as const;

export type Brand = typeof brands[number];
